### ISSUE TITLE
Add option to sync subsonic music files in local and autoload collection

### ISSUE THREAD

**Issue by cedvan** [BlitterStudio/MB_SubSonic#70]
I have a subsonic server navidrome to manage my music collection. 
I play my songs from multiple devices. 

- My phone with symfonium
- On browser with feishin web app 
- On my Windows PC with feishin app

So I can rate my songs with any devices and I use smart playlists to class my library.

But, I have again 2 needs :

- Eventually fix tags if necessary
- Play my songs with my prefered DJ application

To respond this needs, I want use MusicBee on my computer :
- Use MB to edit tags
- Use MB to generate Itunes XML and share my songs/playlists to my DJ app

So I sync my music library in local with Nextcloud app to add my songs to MusicBee.

But with Nextcloud sync solution, I lost my subsonic rating. So I tested your plugin to connect my MB to my Subsonic server. But this plugin have no system to sync music files in local from subsonic.

Possible to add an checkbox option to sync files from the subsonic server to a local folder and load them into the MB collection automatically?

**Comment by midwan** [comment]
I don't think what you want to do is possible from the plugin side, this seems like something MusicBee itself should support first. Also, MusicBee's plugin API would need to allow for some control over it, I assume.
